name: Check Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  verifyPlugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: burrunan/gradle-cache-action@v1

      - name: Test Plugin
        run: ./gradlew test

      - name: Verify Plugin
        run: ./gradlew verifyPlugin

