name: Check Plugin

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  verifyPlugin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: burrunan/gradle-cache-action@v2

      - name: Test Plugin
        run: ./gradlew test --stacktrace

      - name: Verify Plugin
        run: ./gradlew verifyPlugin --stacktrace

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'